config/routes.rb
Rails.application.routes.draw do

  #get 'welcome/index'

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  get "ideas/explore" => "ideas#explore", as: :ideas_explore
  get "ideas/trending" => "ideas#trending", as: :ideas_trending
  get "ideas/popular" => "ideas#popular", as: :ideas_popular

  resources :searches, :only => [:new, :create, :show]
  devise_for :users
  resources :ideas do
  	member do
  		get "like", to: "ideas#upvote"
  		get "dislike", to: "ideas#downvote"
  	end
  	resources :comments
  end

  authenticated :user do
  	root 'ideas#index', as: "authenticated_root"
  end

  root 'welcome#index'

  #root 'ideas#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	def self.search(search)
  		if search
  			where(["title ILIKE ?","%#{search}%"]).all.order("created_at DESC")
  		else
  			all
  		end
  	end

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/search.rb
class Search < ActiveRecord::Base

	def search_ideas
		ideas = Idea.all

		ideas = ideas.where(["title ILIKE ?","%#{keywords}%"]) if keywords.present?
		ideas = ideas.where(["category ILIKE ?","%#{category}%"]) if category.present?

		return ideas
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable
  has_many :ideas
  has_many :comments

  acts_as_messageable

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	helper_method :mailbox, :conversation

	private

	def mailbox
		@mailbox ||= current_user.mailbox
	end

	def conversation
		@conversation ||= mailbox.conversations.find(params[:id])
	end

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@idea = Idea.friendly.find(params[:idea_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.idea_id = @idea.id

		if @comment.save
			redirect_to idea_path(@idea)
		else
			render 'new'
		end
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:notice] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
	before_action :find_idea, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@ideas = Idea.search(params[:search]).all.order("created_at DESC")
	end

	def show
		@comments = Comment.where(idea_id: @idea)
		@random_idea = Idea.where.not(id: @idea).order("RANDOM()").first
	end

	def new
		@idea = current_user.ideas.build
	end

	def create
		@idea = current_user.ideas.build(idea_params)

		if @idea.save
			@user = current_user

			PostMailer.post_created(@user).deliver
			redirect_to @idea
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @idea.update(idea_params)
			redirect_to @idea
		else
			render 'edit'
		end
	end

	def destroy
		@idea.destroy
		redirect_to root_path
	end

	def upvote
		@idea.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@idea.downvote_by current_user
		redirect_to :back
	end

	def explore
		@ideas = Idea.search(params[:search]).all.order("created_at DESC")
	end

	def trending
		@ideas = Idea.search(params[:search]).all.order("comments_count, created_at DESC")
	end

	def popular
		@ideas = Idea.search(params[:search]).all.order("created_at DESC")
	end

	private

	def find_idea
		@idea = Idea.friendly.find(params[:id])
	end

	def idea_params
		params.require(:idea).permit(:title, :link, :description, :image, :category, :slug)
	end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

	def inbox
		@inbox = mailbox.inbox
		@active = :inbox
	end

	def sent
		@sent = mailbox.sentbox
		@active = :sent
	end

	def trash
		@trash = mailbox.trash
		@active = :trash
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new
		@search = Search.new
		@categories = Idea.uniq.pluck(:category)
	end

	def create
		@search = Search.create(search_params)
		redirect_to @search 
	end

	def show
		@search = Search.find(params[:id])
	end

	private

	def search_params
		params.require(:search).permit(:keywords, :category)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_page(active_page)
		@active == active_page ? "active" : ""
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
	
	def unread_messages_count
		# how to get the number of unread messages for the current user
		# using mailboxer
		mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end
	
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@idea, @idea.comments.build]) do |f|
	= f.input :content, label: "Reply to thread", class: "reply-thread"
	= f.button :submit, class: "button"

app/views/conversations/_conversation.html.haml
.media
  .media-left
    %a{:href => "#"}
      %img.media-object{:alt => "...", :src => "http://placehold.it/64x64"}/
  .media-body
    %h4.media-heading
      = conversation.originator.name
      %br/
      %small
        %b Subject:
        = conversation.subject
      %br/
      %small
        %b Date:
        = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation)

app/views/conversations/_form.html.haml
= form_for :conversation, url: :conversations, html: { class: "" } do |f|
  .form-group
    = f.label :recipients, class: "text optional"
    = f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })
  .form-group
    = f.label :subject, class: "text optional"
    = f.text_field :subject, placeholder: "Subject", class: "convo-subject"
  .form-group
    = f.label :message, class: "text optional"
    = f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4
  = f.submit "Send Message", class: "btn btn-success"

app/views/conversations/_messages.html.haml
- @receipts.each do |receipt|
  - message = receipt.message
  .media
    .media-left
      / user avators can go here
      %a{:href => "#"}
        %img.media-object{:alt => "...", :src => "http://placehold.it/64x64"}/
    .media-body
      %h4.media-heading
        = message.sender.name
        %br/
        %small
          %b Subject:
          = message.subject
        %br/
        %small
          %b Date:
          = message.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
      = message.body

app/views/conversations/new.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: true }

app/views/conversations/show.html.haml
.mailbox-wrapper
  .row
    .spacer
    .col-md-12
      = link_to "Compose", new_conversation_path, class: "btn btn-success"
      = link_to "Inbox", mailbox_inbox_path, class: "btn"
      = link_to "Sent", mailbox_sent_path, class: "btn"
      = link_to "Trash", mailbox_trash_path, class: "btn"
      - conversation = @conversation
      .col-trash
        - if conversation.is_trashed?(current_user)
          = link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post
        - else
          = link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post, |
            data: {confirm: 'Are you sure?'}                                                                        |

  .row
    .spacer
    -# .col-md-4
    -#   .panel.panel-default
    -#     .panel-body
    -#       = render 'mailbox/folders'
    .col-md-12
      .panel.panel-default
        .panel-body
          = render partial: 'messages'
        .panel-footer
          / Reply Form
          = form_for :message, url: reply_conversation_path(conversation) do |f|
            .form-group
              = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
            = f.submit "Reply", class: 'btn btn-danger pull-right'
          .clearfix

app/views/ideas/_form.html.haml
= simple_form_for @idea do |f|
  = f.input :image, label: false, placeholder: "Image..."
  = f.input :title, label: false, placeholder: "Idea Title"
  = f.input :link, label: false, placeholder: "Link"
  = f.input :category, label: false, placeholder: "Catergory"
  = f.input :description, label: false, placeholder: "Description"

  = f.button :submit

-# %form.cd-form.floating-labels{}
-#   = simple_form_for @idea do |f|
-#     %fieldset
-#       .icon
-#         -# %label.cd-label{:for => "cd-name"} Name
-#         -# %input#cd-name.user{:name => "cd-name", :required => "", :type => "text"}/
-#         = f.input :image, label: false, required: false, autofocus: true, id: "login__username", class: "form__input", placeholder: "Email"
-#       .icon
-#         -# %label.cd-label{:for => "cd-company"} Company
-#         -# %input#cd-company.company{:name => "cd-company", :type => "text"}/
-#         = f.input :title, label: false, required: false, autofocus: true, id: "user", class: "user", placeholder: "Idea Title"
-#       .icon
-#         -# %label.cd-label{:for => "cd-email"} Email
-#         = f.input :link, label: false, required: false, autofocus: true, id: "user", class: "user", placeholder: "Link"
-#       %div
-#         %p
-#           = f.input :link, label: false, required: false, autofocus: true, id: "user", class: "user", placeholder: "Category"
-#       .icon
-#         -# %label.cd-label{:for => "cd-textarea"} Project description
-#         = f.input :description, label: false, required: false, autofocus: true, id: "user", class: "user", placeholder: "Explain your idea, and be brief..."
-#       %div
-#         %input{:type => "submit", :value => "Share Idea"}

app/views/ideas/edit.html.haml
= render 'form'

app/views/ideas/explore.html.haml
%h1 Hi, I am in explore

app/views/ideas/index.html.haml
- if user_signed_in?
	%p#intro
		Hello,
		= current_user.name
		%br/
		%span
			Share your idea and see what's others are thinking.
- else
	%p#intro
		What's your idea?
		%br/
		%span
			Share your idea and see what others are thinking.
#posts
	- @ideas.each do |idea|
		.post
			.post_image
				= link_to (image_tag idea.image.url(:small)), idea
			.post_content
				.title
					%h2= link_to idea.title, idea
				.data.clearfix
					%p.username
						= idea.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= idea.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= idea.get_likes.size

app/views/ideas/new.html.haml
= render 'form'

app/views/ideas/popular.html.haml
#posts
	- @ideas.each do |idea|
		.post
			.post_image
				= link_to (image_tag idea.image.url(:small)), idea
			.post_content
				.title
					%h2= link_to idea.title, idea
				.data.clearfix
					%p.username
						= idea.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= idea.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= idea.get_likes.size

app/views/ideas/show.html.haml
.session-wrapper
	#post_show
		%h1= @idea.title
		%p.username
			Shared by
			= @idea.user.name
			about
			= time_ago_in_words(@idea.created_at)
		.clearfix
			.post_image_description
				= image_tag @idea.image.url(:medium)
				.description= simple_format(@idea.description)
				Category:
				= @idea.category
			.post_data
				= link_to "Visit Link", @idea.link, class: "button"
				= link_to like_idea_path(@idea), method: :get, class: "data" do
					%i.fa.fa-thumbs-o-up
					= pluralize(@idea.get_upvotes.size, "Like")
				= link_to dislike_idea_path(@idea), method: :get, class: "data" do
					%i.fa.fa-thumbs-o-down
					= pluralize(@idea.get_downvotes.size, "Dislike")
				%p.data
					%i.fa.fa-comments-o
					= pluralize(@idea.comments.count, "Comment")
				- if @idea.user == current_user
					= link_to "Edit", edit_idea_path(@idea), class: "data"
					= link_to "Delete", idea_path(@idea), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
			#random_post
				%h3 Like what you see? Check out other people's idea!
				.post
					.post_image
						= link_to (image_tag @random_idea.image.url(:medium)), idea_path(@random_idea)
					.post_content
						.title
							%h2= link_to @random_idea.title, idea_path(@random_idea)
						.data.clearfix
							%p.username
								Shared by
								= @random_idea.user.name
							%p.buttons
								%span
									%i.fa.fa-comments-o
									= @random_idea.comments.count
								%span
									%i.fa.fa-thumbs-o-up
									= @random_idea.get_likes.size

	#comments
		%h1.comment_count= pluralize(@idea.comments.count, "Comment")
		- @comments.each do |comment|
			.comment
				%p.username= comment.user.name
				%p.date= l(comment.created_at, format: '%B, %d %Y, %H:%M')
				%p.content= comment.content

		= render "comments/form"

app/views/ideas/trending.html.haml
%h1 Explore

#posts
	- @ideas.each do |idea|
		.post
			.post_image
				= link_to (image_tag idea.image.url(:small)), idea
			.post_content
				.title
					%h2= link_to idea.title, idea
				.data.clearfix
					%p.username
						= idea.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= idea.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= idea.get_likes.size

app/views/layouts/_footer.html.haml
%footer
	%p
		&copy; 2016 Inventors. Developed by
		%a.hsy{:href => "http://github.com/hassanyf"} Hassan M. Yousuf 
	%ul.footer-bottom
		%li
			%a{:href => "mailto:hello@inventors.pk"} hello@inventors.pk
		%li
			%a{:href => "terms/"} Terms & License
		%li
			%a{:href => "faq/"} FAQ
		%li
			%a{:href => "getting-started/"} Getting started
	%ul.footer-bottom
		%li
			%a.img-replace.github{:href => ""} Github
		%li
			%a.img-replace.twitter{:href => ""} Twitter
		%li
			%a.img-replace.facebook{:href => ""} Facebook
		%li
			%a.img-replace.google{:href => ""} Instagram

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Inventors
	- if controller_name == "welcome" && action_name == "index"
		= stylesheet_link_tag 'screen'
		= javascript_include_tag 'modernizr-2.6.2.min'
		= javascript_include_tag 'main.min'
	- else
		= stylesheet_link_tag    'application', media: 'all'
		= stylesheet_link_tag    'global', media: 'all'
		= javascript_include_tag 'application'
		-# %link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet"}
		%script{:charset => "utf-8", :src => "/function.js", :type => "text/javascript"}
		%meta{:content => "width=device-width", :name => "viewport"}
		%link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,100,300,500", :rel => "stylesheet"}
		%link{:rel => "stylesheet", :href => "https://necolas.github.io/normalize.css/3.0.3/normalize.css"}
		%script{:charset => "utf-8", :src => "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js", :type => "text/javascript"}
		%script{:charset => "utf-8", :src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js", :type => "text/javascript"}
		%script{:charset => "utf-8", :src => "http://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/1.4.11/jquery.scrollTo.min.js", :type => "text/javascript"}
		%script{:charset => "utf-8", :src => "http://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js", :type => "text/javascript"}
		%link{:rel => "stylesheet", :href => "/bootstrap.css"}
		%link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
		%meta{:content => "Discover new ideas or share your own.", :name => "description"}
		%meta{:content => "idea sharing platform", :name => "keywords"}
		%meta{:content => "hassan yousuf", :name => "author"}
		%meta{:content => "(c) 2016 inventors", :name => "copyright"}
		%meta{:content => "width=device-width", :name => "viewport"}
	= csrf_meta_tags
%body
	- if notice
		#notice_wrapper
			%p.notice= notice
	- elsif alert
		#notice_wrapper
			%p.alert= alert

	- if controller_name == "welcome"
		.wrapper
			= yield

	- elsif controller_name != "welcome"
		%aside#sidebar.nano
			.nano-content
				.logo-container
					=link_to "Inventors", root_path
				- if user_signed_in?
					= link_to "Add an Idea", new_idea_path, class: "compose-button"
					%menu.menu-segment
						%ul
							%li
								= link_to "Settings", edit_user_registration_path
							%li
								- if user_signed_in?
									.outer-mailbox
										.outer-mailbox-2
											= link_to unread_messages_count
										.outer-mailbox-1
											= link_to "Inbox", mailbox_inbox_path, class: "li-1"
							%li
								= link_to "Sign Out", destroy_user_session_path, :method => :delete
				- else
					.login-notice
						%p
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

		%main#main
			- if user_signed_in?
				.overlay
				%header.header
					%nav
						.search-box
							- if controller_name != "welcome"
								= form_tag ideas_path, :method => 'get' do
									= text_field_tag :search, params[:search], :placeholder => "Search..."

					%ul.top-static-bar
						%li
							%a{:href => "/ideas/explore"}
								Explore
						%li
							%a{:href => "/"}
								Trending
						%li
							%a{:href => "/popular"}
								Most Popular
						%li
							%a{:href => "/"}
								Most Viewed
						%li
							%a{:href => "/"}
								Recent

			#main-nano-wrapper.nano
				.nano-content
					= yield

		-# - if controller_name != "welcome"
		-# 	= render 'layouts/footer'

	:javascript
		$(document).ready(function(){
			setTimeout(function(){
				$('#notice_wrapper').fadeOut("slow", function(){
					$(this).remove();
				})
			}, 4000);
		});

app/views/mailbox/_folder_view.html.haml
.mailbox-wrapper
  .row
    .spacer
    .col-md-12
      = link_to "Compose", new_conversation_path, class: "btn btn-success"
      = link_to "Inbox", mailbox_inbox_path, class: "btn"
      = link_to "Sent", mailbox_sent_path, class: "btn"
      = link_to "Trash", mailbox_trash_path, class: "btn"
      .spacer
    -# .col-md-4
    -#   .panel.panel-default
    -#     .panel-body
    -#       = render 'mailbox/folders'
    .col-md-12
      .panel.panel-default
        .panel-body
          - if is_conversation
            = render 'conversations/form'
          - else
            = render partial: 'conversations/conversation', collection: messages

app/views/mailbox/_folders.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{:class => active_page(:inbox)}
    = link_to mailbox_inbox_path do
      %span.label.label-danger.pull-right= unread_messages_count
      %em.fa.fa-inbox.fa-lg
      %span Inbox
  %li{:class => active_page(:sent)}
    = link_to mailbox_sent_path do
      %em.fa.fa-paper-plane-o.fa-lg
      %span Sent
  %li{:class => active_page(:trash)}
    = link_to mailbox_trash_path do
      %em.fa.fa-trash-o.fa-lg
      %span Trash

app/views/mailbox/inbox.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox }

app/views/mailbox/sent.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent }

app/views/mailbox/trash.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash }

app/views/searches/new.html.haml
%h1 Advanced Search
= form_for @search do |s|
  .field
    = s.label :keywords
    %br/
    = s.text_field :keywords
  .field
    = s.label :category
    %br/
    = s.select :category, options_for_select(@categories), :include_blank => true
  .actions
    = s.submit "Search", class: "pure-button"

app/views/searches/show.html.haml
%h1 Search Result

- if @search.search_ideas.empty?
  %p No ideas found!

- else
  - @search.search_ideas.each do |idea| 
    %br/
    #posts
      .post
        .post_image
          = link_to (image_tag idea.image.url(:small)), idea
        .post_content
          .title
            %h2= link_to idea.title, idea
          .data.clearfix
            %p.username
              Shared by
              = idea.user.name
            %p.buttons
              %span
                %i.fa.fa-comments-o
                = idea.comments.count
              %span
                %i.fa.fa-thumbs-o-up
                = idea.get_likes.size